name: push to github
on:
  push:
    branches:
    - 'master'
jobs:
  deploy:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      # from: https://github.com/jsonhc/topic.git
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: push change files to github
        run: |
          mkdir public
          echo "test" > another.json
          
      # 将目录public推送到文件仓库 https://github.com/jsonhc/git_test.git
      - name: Deploy directory to another github repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }} 
          external_repository: jsonhc/git_test
          publish_branch: master
          publish_dir: ./public
          keep_files: true
