name: push to github
on:
  push:
    branches:
    - 'master'
jobs:
  deploy:
    name: Deploy Hexo Public To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      # from: https://github.com/jsonhc/topic.git
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: Run Trivy vulnerability scanner in repo mode
        id: scan_vulnerability
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          output: 'trivy-results.txt'
          severity: 'HIGH,CRITICAL'

      - name: Build
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "-DskipTests clean install"

      - name: push change files to github
        run: |
          ls -l
          mkdir -p public
          sudo mv trivy-results.txt public/
          sudo mv target public/
          
      # 将目录public推送到文件仓库 https://github.com/jsonhc/git_test.git
      - name: Deploy directory to another github repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }} 
          external_repository: jsonhc/git_test
          publish_branch: master
          publish_dir: ./public
          keep_files: true
          allow_empty_commit: true
