name: push to github
on:
  push:
    branches:
    - 'master'
jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: config git
        run: |
          git clone https://jsonhc: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@github.com/jsonhc/git_test.git
          cd git_test
          echo "hello world" > test.json111
          git add .
          git commit -m "create test.json111"
          git push origin master
