name: Build and Push image
on:
  push:
    branches:
    - 'master'
jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Run Trivy vulnerability scanner in repo mode
        id: scan_vulnerability
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          output: 'trivy-results.txt'
          severity: 'HIGH,CRITICAL'
      
      - name: Build
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "-DskipTests clean install"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "jsonhcstart"
          password: "HHq123456*"

      - name: test war
        run: ls -l && ls -l target

      - name: Build and Push container images
        uses: docker/build-push-action@v4.0.0
        id: build-and-push
        with:
          push: true
          tags: jsonhcstart/topic:${{ github.sha }}
