name: Build and Push image
on:
  push:
    branches:
    - 'master'
jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Run Trivy vulnerability scanner in repo mode
        id: scan_vulnerability
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          output: 'trivy-results.txt'
          severity: 'HIGH,CRITICAL'
      
      - name: Slack Notification when trivy fails
        if: success() && job.steps.scan_vulnerability.status == failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "jsonhc"
          SLACK_COLOR: "failure"
          SLACK_MESSAGE: "Failed trivy scan, see below report"
          SLACK_TITLE: "Scan failed"
          SLACK_USERNAME: "jsonhc"
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

      - name: upload the trivy report
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: "xoxb-7117038586977-7101470931349-XtYgMrxvbi13dxsUIEJieYLE"
          channel_id: "C073F15LV1P"
          file_path: '${{ github.workspace }}/trivy-results.txt'
          initial_comment: 'upload the trivy report'
