name: push to github
on:
  push:
    branches:
    - 'master'
jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: config git
        run: |
          git clone https://github.com/jsonhc/git_test.git
          cd git_test
          echo "hello world" > test.json
          git config user.name "jsonhc"
          git config user.email "json_hc@163.com"
          git add .
          git commit -m "create test.json"

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          repository: jsonhc/git_test
          force: true
