name: push to github
on:
  push:
    branches:
    - 'master'
jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: config git
        run: |
          echo "hello world" > test.json1
          git config user.name "jsonhc"
          git config user.email "json_hc@163.com"
          git add .
          git commit -m "create test.json"

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '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'
          repository: jsonhc/git_test
