name: push to github
on:
  push:
    branches:
    - 'master'
jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: config git
        run: |
          echo "hello world" > test.json
          git config user.name "jsonhc"
          git config user.email "json_hc@163.com"
          git add .
          git commot -m "create test.json"

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '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'
