name: push to github
on:
  push:
    branches:
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Create local changes
      run: |
        echo "test to push" > push.json
    - name: Commit files
      run: |
        git config --local user.email "json_hc@163.com"
        git config --local user.name "jsonhc"
        git add .
        git commit -a -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
